language: generic
sudo: require
services:
    - docker

before_install:
  - docker build -t bretts89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bretts89/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-882330273289"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY