language: generic
sudo: require
services:
    - docker


before_install:
  - docker build -t bretts89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bretts89/docker-react npm run test -- --coverage
